### PR TITLE
Added JWT Token Authorization and Slightly Modified File Structure.

### PR DESCRIPTION
**Pull request by Knathmer**
# Backend Changes
1. **Login Function Update**: 
   - Modified the `login` function in `authController.js` to create a JWT token that corresponds to the role of the user logging in (admin, doctor, patient).
   
2. **New Middleware Functions**:
   - Created a `middleware` folder.
   - Added `auth.js` with two key functions:
     - `verifyToken`: Ensures the JWT token exists.
     - `authorizeRole`: Ensures the user's role matches the permissions for the route they are trying to access.

# Front-end Changes
1. **App.jsx Update**:
   - Moved `App.jsx` out of the `components` folder for better structure.
   
2. **Routing Folder**:
   - Created a new `routing` folder to break down user functionality in a more organized and modular way.
   
3. **User Dashboards**:
   - Created dashboards for all user types (admin, doctor, patient).

## Front-end Authorization Changes
1. **ProtectedRoute Higher-Order Component**:
   - Created a `protectedroute.jsx` component that acts as middleware for protected routes.
   - Wrapped all protected routes in `App.jsx` with `ProtectedRoute` to ensure only verified users can access them.
   
2. **Role-Based Routing**:
   - If a user accesses a protected route (e.g., `/patient`, `/doctor`, `/admin`), the request is routed to the respective routing file contained within the `routing` folder.
   - **This allows easy and modular management of user-specific functionality**.

# Other Minor Changes
1. **Forbidden Access Page**:
   - Added a `forbidden.jsx` component that renders when an unauthorized route is accessed.
   
2. **Code Documentation**:
   - Added comments to explain key parts of the code and changes made for clarity.
   
3. **ES Module Imports**
   - Fixed ES module imports on the backend.
# Note
Make sure to include .env file that contains the JWT secret key (Of your choosing) in the backend folder. The format is like so `JWT_SECRET=anything`.

Create the `.env` file.
Copy paste the above code.
Change `anything` to some password.

### CODE REVIEW

**Comment by adamgj3030** [comment]
couldnt register and couldnt login with any of the exisiting data BUT the basic functionality is there

**Comment by Knathmer** [comment]
> couldnt register and couldnt login with any of the exisiting data BUT the basic functionality is there

Weird, I made some last second changes maybe that's the problem. Let me fix.

edit: I really need to start unit testing

**Comment by Knathmer** [comment]
# Changes
1. Created database transactions. This ensures that for some transaction, if one part fails, then all will fail. This was implemented for registration
2. Added debug statements to keep track of registration
3. Fixed authentication routing after logging in.
4. Fixed the pool import from the `database.js` file.
5. Changed the `mysql` import to `mysql2/promise`.

Do note that _at the moment_ we do not have a registration feature for doctors and admins.

@adamgj3030 Give it a try now.

**Review by anthonycasarta — APPROVED** [review]
looks good

**Pull request merged**
