### PR TITLE
Patient Dashboard 

### PR DESCRIPTION
**Pull request by issantidote**
Updated the three dashboards to be dynamic 
- upcoming appointments: features the status of appoint, date, time, and doctor
- medical status: includes the status and req date
- billing status : shows due date and current status

tested on peefart@gmail.com

extra notes:
renamed a couple of functions/files for clarity

### CODE REVIEW

**Comment by Sthiber** [comment]
Getting an error in the Upcoming Appointments container "Error: Failed to fetch appointments". This is being generated by you get in fetchAppointments function in UpcomingAppointmentsContainer.jsx

const response = await axios.get("http://localhost:3000/dataFetch/get-appointment-dashboard"


Screenshot 2024-11-12 at 12 58 28 AM
Screenshot 2024-11-12 at 12 59 15 AM

**Review by Sthiber — APPROVED** [review]
Works well just has that GET error probably something with the GET query in the backend.

**Comment by Sthiber** [comment]
Good job!

**Comment by issantidote** [comment]
Additional updates:
- fixed Upcoming Appointment backend issues. Earlier it register an empty array as an error. 
- add scroll feature to all the dashboard components 
- merge conflicts resolved

**Pull request merged**
